disallowed-methods = [
    # f64
    { path = "f64::sin", reason = "non-deterministic floating-point math, use Angle::sin or libm::sin" },
    { path = "f64::cos", reason = "non-deterministic floating-point math, use Angle::cos or libm::cos" },
    { path = "f64::tan", reason = "non-deterministic floating-point math, use Angle::tan or libm::tan" },
    { path = "f64::asin", reason = "non-deterministic floating-point math, use Angle::asin or libm::asin" },
    { path = "f64::acos", reason = "non-deterministic floating-point math, use Angle::acos or libm::acos" },
    { path = "f64::atan", reason = "non-deterministic floating-point math, use Angle::atan or libm::atan" },
    { path = "f64::atan2", reason = "non-deterministic floating-point math, use Angle::atan2 or libm::atan2" },
    { path = "f64::sin_cos", reason = "non-deterministic floating-point math, use separate calls" },
    { path = "f64::sinh", reason = "non-deterministic floating-point math, use libm::sinh" },
    { path = "f64::cosh", reason = "non-deterministic floating-point math, use libm::cosh" },
    { path = "f64::tanh", reason = "non-deterministic floating-point math, use libm::tanh" },
    { path = "f64::asinh", reason = "non-deterministic floating-point math, use libm::asinh" },
    { path = "f64::acosh", reason = "non-deterministic floating-point math, use libm::acosh" },
    { path = "f64::atanh", reason = "non-deterministic floating-point math, use libm::atanh" },
    { path = "f64::powi", reason = "non-deterministic floating-point math, use Scalar::powi" },
    { path = "f64::powf", reason = "non-deterministic floating-point math, use libm::pow" },
    { path = "f64::exp", reason = "non-deterministic floating-point math, use libm::exp" },
    { path = "f64::exp2", reason = "non-deterministic floating-point math, use libm::exp2" },
    { path = "f64::ln", reason = "non-deterministic floating-point math, use libm::log" },
    { path = "f64::log", reason = "non-deterministic floating-point math, use libm::log(num) / libm::log(base)" },
    { path = "f64::log2", reason = "non-deterministic floating-point math, use libm::log2" },
    { path = "f64::log10", reason = "non-deterministic floating-point math, use libm::log10" },
    { path = "f64::exp_m1", reason = "non-deterministic floating-point math" },
    { path = "f64::ln_1p", reason = "non-deterministic floating-point math" },
    { path = "f64::cbrt", reason = "non-deterministic floating-point math, use libm::cbrt" },
    { path = "f64::hypot", reason = "non-deterministic floating-point math, use Point::hypot" },

    # f32
    { path = "f32::sin", reason = "non-deterministic floating-point math, use Angle::sin or libm::sinf" },
    { path = "f32::cos", reason = "non-deterministic floating-point math, use Angle::cos or libm::cosf" },
    { path = "f32::tan", reason = "non-deterministic floating-point math, use Angle::tan or libm::tanf" },
    { path = "f32::asin", reason = "non-deterministic floating-point math, use Angle::asin or libm::asinf" },
    { path = "f32::acos", reason = "non-deterministic floating-point math, use Angle::acos or libm::acosf" },
    { path = "f32::atan", reason = "non-deterministic floating-point math, use Angle::atan or libm::atanf" },
    { path = "f32::atan2", reason = "non-deterministic floating-point math, use Angle::atan2 or libm::atan2f" },
    { path = "f32::sin_cos", reason = "non-deterministic floating-point math, use separate calls" },
    { path = "f32::sinh", reason = "non-deterministic floating-point math, use libm::sinhf" },
    { path = "f32::cosh", reason = "non-deterministic floating-point math, use libm::coshf" },
    { path = "f32::tanh", reason = "non-deterministic floating-point math, use libm::tanhf" },
    { path = "f32::asinh", reason = "non-deterministic floating-point math, use libm::asinhf" },
    { path = "f32::acosh", reason = "non-deterministic floating-point math, use libm::acoshf" },
    { path = "f32::atanh", reason = "non-deterministic floating-point math, use libm::atanhf" },
    { path = "f32::powi", reason = "non-deterministic floating-point math, use Scalar::powi" },
    { path = "f32::powf", reason = "non-deterministic floating-point math, use libm::powf" },
    { path = "f32::exp", reason = "non-deterministic floating-point math, use libm::expf" },
    { path = "f32::exp2", reason = "non-deterministic floating-point math, use libm::exp2f" },
    { path = "f32::ln", reason = "non-deterministic floating-point math, use libm::logf" },
    { path = "f32::log", reason = "non-deterministic floating-point math, use libm::logf(num) / libm::logf(base)" },
    { path = "f32::log2", reason = "non-deterministic floating-point math, use libm::log2f" },
    { path = "f32::log10", reason = "non-deterministic floating-point math, use libm::log10f" },
    { path = "f32::exp_m1", reason = "non-deterministic floating-point math" },
    { path = "f32::ln_1p", reason = "non-deterministic floating-point math" },
    { path = "f32::cbrt", reason = "non-deterministic floating-point math, use libm::cbrtf" },
    { path = "f32::hypot", reason = "non-deterministic floating-point math, use Point::hypot" },
]
