[package]
name = "typst-library"
version = "0.3.0"
authors = ["The Typst Project Developers"]
edition = "2021"
description = "The standard library for Typst."
homepage = "https://typst.app"
repository = "https://github.com/typst/typst"
license = "Apache-2.0"
keywords = ["typst"]

[lib]
test = false
doctest = false
bench = false

[dependencies]
typst = { path = ".." }
chinese-number = { version = "0.7.2", default-features = false, features = ["number-to-chinese"] }
comemo = "0.2.2"
csv = "1"
ecow = "0.1"
hayagriva = "0.3"
hypher = "0.1"
kurbo = "0.8"
lipsum = "0.9"
log = "0.4"
once_cell = "1"
roxmltree = "0.14"
rustybuzz = "0.5"
serde_json = "1"
serde_yaml = "0.8"
smallvec = "1.10"
syntect = { version = "5", default-features = false, features = ["default-syntaxes", "regex-fancy"] }
toml = { version = "0.7.3", default-features = false, features = ["parse"] }
tracing = "0.1.37"
ttf-parser = "0.18.1"
typed-arena = "2"
unicode-bidi = "0.3.13"
unicode-math-class = "0.1"
unicode-script = "0.5"
unicode-segmentation = "1"
xi-unicode = "0.3"
time = {version = "0.3.20", features = ["formatting"]}
