[package]
name = "typst-library"
version = "0.0.0"
authors = ["The Typst Project Developers"]
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
typst = { path = ".." }
comemo = { git = "https://github.com/typst/comemo" }
csv = "1"
ecow = "0.1"
hayagriva = { git = "https://github.com/typst/hayagriva" }
hypher = "0.1"
kurbo = "0.8"
lipsum = { git = "https://github.com/reknih/lipsum" }
log = "0.4"
once_cell = "1"
roxmltree = "0.14"
rustybuzz = "0.5"
serde_json = "1"
smallvec = "1.10"
syntect = { version = "5", default-features = false, features = ["default-syntaxes", "regex-fancy"] }
ttf-parser = "0.18.1"
typed-arena = "2"
unicode-bidi = "0.3.5"
unicode-math-class = { git = "https://github.com/typst/unicode-math-class" }
unicode-script = "0.5"
unicode-segmentation = "1"
xi-unicode = "0.3"
