[package]
name = "typst-docs"
version = "0.0.0"
authors = ["The Typst Project Developers"]
edition = "2021"

[lib]
doctest = false
bench = false

[dependencies]
typst = { path = ".." }
typst-library = { path = "../library" }
unscanny = "0.1"
include_dir = "0.7"
pulldown-cmark = "0.9"
comemo = "0.2"
serde = "1"
serde_yaml = "0.8"
heck = "0.4"
yaml-front-matter = "0.1"
unicode_names2 = "0.6.0"
once_cell = "1"
